(in-package :asm-mips)

(defun lick-it (&optional (filename "pestilence/to4fpu/preparee.o"))
  (let* ((b-p (symbol-function (find-symbol "PARSE" (find-package :bintype))))
         (e-e (find-symbol "EHDR" (find-package :elf)))
         (e-e-s (symbol-function (find-symbol "EHDR-SECTIONS" (find-package :elf))))
         (e-s-e-p (symbol-function (find-symbol "SHDR-EXECUTABLE-P" (find-package :elf))))
         (vector (pergamum:file-as-vector filename))
         (ehdr (funcall b-p e-e vector))
         (section (car (funcall e-e-s ehdr e-s-e-p)))
         (bbs (unturing:insn-vector-to-basic-blocks mips-assembly:*mips-isa* section)))
    (unturing::pprint-bignode-graph-linear bbs)))